<?php

declare(strict_types=1);

namespace GlpiPlugin\Uimanager\Branding;

final class LogoInjection
{
    public function __construct(private readonly BrandingAssets $assets = new BrandingAssets())
    {
    }

    /**
     * Controller-relative URLs are resolved by the browser against the runtime
     * endpoint URL generated by GLPI's plugin router.
     *
     * @param array<string, string> $branding
     * @return array{expanded_logo: string, collapsed_logo: string, application_name: string}
     */
    public function resolve(array $branding): array
    {
        return [
            'expanded_logo' => $this->urlForAsset($branding['expanded_logo'] ?? ''),
            'collapsed_logo' => $this->urlForAsset($branding['collapsed_logo'] ?? ''),
            'application_name' => trim($branding['application_name'] ?? ''),
        ];
    }

    public function urlForAsset(string $name): string
    {
        $delivery = $this->assets->delivery($name);
        if ($delivery === null) {
            return '';
        }
        $modified = filemtime($delivery['path']);
        if ($modified === false) {
            return '';
        }

        return 'branding.asset.php?' . http_build_query([
            'file' => $name,
            'v' => $modified,
        ], '', '&', PHP_QUERY_RFC3986);
    }
}
